### ISSUE TITLE
net.connect is not a function

### ISSUE THREAD

**Issue by aamakerlsa** [call-a3/browserify-notify#2]
trying to get node-notifier working in browser and came across this npm package.... I am getting the following error in the browser console after running 
`browserify -p browserify-notify bundle.js > dist/bundle.js`

error from browser console:

Uncaught TypeError: net.connect is not a function
    at module.exports (bundle.js:637)
    at Growl.notify (bundle.js:1392)
    at Object.1.node-notifier (bundle.js:15)
    at o (bundle.js:1)
    at r (bundle.js:1)
    at bundle.js:1

I guess its some dependency that can only run server-side and NOT in browser, but is this something I can work around somehow?  My use case is just in a web app with NGINX as the server on port  80

**Comment by call-a3** [comment]
To start off, I don't actively maintain this package any more, since I've moved on from using browserify myself... (just in case this wasn't clear yet :stuck_out_tongue:) However, let's take a stab at this...

The use-case for this package is when you're running browserify on your development machine, so you can get faster/more visible feedback on builds as they pass/fail. So I'm a bit confused by your request to run it "in a browser". Do you mean that you are running browserify inside a browser and you would like to get notifications notifications from your browser? Or do you mean you are running browserify on some remote development server and you would like to get the notifications inside your (local) browser where you are checking the build results?
